version: "3.3"

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql-local
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./script:/docker-entrypoint-initdb.d
      - /d/docker/SHARED_VOLUME_WITH_DOCKER/mysql_db_data:/var/lib/mysql